{ title: "Nº Guía", field: "nroguia" },
{ title: "Rut Cliente", field: "rutcliente" },
{ title: "Estado", field: "estado" },
{ title: "Peso Total (kg)", field: "pesototal" },
{ title: "Cliente", field: "cliente" },
{ title: "Fecha Despacho", field: "fechadespacho" },
{ title: "Hora escaneo", field: "horaescaneo" },
{ title: "Nº Bultos", field: "nrobultos" },
{ title: "Producto", field: "producto" },
{ title: "Nave", field: "nave" },
{ title: "Turno", field: "turno" },
{ title: "Puerto", field: "puerto" }
